flowchart TD

    USER(["Usuario — Navegador"])

    subgraph docker["Docker Compose"]

        subgraph fe_layer["Frontend — puerto 3000"]
            NG["Nginx — SPA React -- /api/ /admin/ /static/ -- /ws/ WebSocket Upgrade"]
        end

        subgraph api_layer["Backend — Daphne ASGI — puerto 8000"]
            API["Django REST Framework -- JWT · Strategy por país · Whitenoise"]
            CH["Django Channels -- WebSockets timeline en tiempo real"]
        end

        subgraph workers_layer["Workers"]
            CL["Celery Worker x2 -- Validación · Buró bancario · Reglas · Webhooks"]
        end

        subgraph data_layer["Datos"]
            RD["Redis — puerto 6379 -- DB0: broker · DB1: caché · DB2: channel layer"]
            PG["PostgreSQL 16 — puerto 5432"]
        end

    end

    subgraph ext["Servicios externos"]
        BK["Proveedores bancarios — mock MX · CO"]
        WH["Webhooks — Salientes decisión final"]
    end

    USER --> NG
    NG -- "HTTP /api/ /admin/ /static/" --> API
    NG -- "WS /ws/ Upgrade" --> CH
    API --> PG
    API --> RD
    CL --> PG
    CL --> BK
    CL --> WH
    CL --> RD
    CH --> RD
    RD --> CL

    style USER fill:#D3D1C7,stroke:#5F5E5A,color:#2C2C2A
    style NG fill:#D3D1C7,stroke:#5F5E5A,color:#2C2C2A
    style API fill:#CECBF6,stroke:#534AB7,color:#26215C
    style CH fill:#CECBF6,stroke:#534AB7,color:#26215C
    style RD fill:#FAC775,stroke:#854F0B,color:#412402
    style CL fill:#F5C4B3,stroke:#993C1D,color:#4A1B0C
    style PG fill:#B5D4F4,stroke:#185FA5,color:#042C53
    style BK fill:#C0DD97,stroke:#3B6D11,color:#173404
    style WH fill:#C0DD97,stroke:#3B6D11,color:#173404
