# Generated by Django 6.0.4 on 2026-04-08 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('ES', 'España'), ('PT', 'Portugal'), ('IT', 'Italia'), ('MX', 'México'), ('CO', 'Colombia'), ('BR', 'Brasil')], max_length=2)),
                ('full_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI (España)'), ('NIF', 'NIF (Portugal)'), ('CODICE_FISCALE', 'Codice Fiscale (Italia)'), ('CURP', 'CURP (México)'), ('CC', 'Cédula de Ciudadanía (Colombia)'), ('CPF', 'CPF (Brasil)')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_applications',
                'ordering': ['-requested_at'],
            },
        ),
    ]
