# Generated by Django 6.0.4 on 2026-04-09 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='applications.creditapplication')),
            ],
            options={
                'db_table': 'application_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BankProviderData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('account_status', models.CharField(max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_data', to='applications.creditapplication')),
            ],
            options={
                'db_table': 'bank_provider_data',
            },
        ),
        migrations.CreateModel(
            name='CountryValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('passed', models.BooleanField()),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='applications.creditapplication')),
            ],
            options={
                'db_table': 'country_validations',
            },
        ),
    ]
