# Generated by Django 6.0.4 on 2026-04-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationstatushistory_bankproviderdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=50)),
                ('document_hint', models.CharField(max_length=200)),
                ('document_example', models.CharField(max_length=100)),
                ('document_regex', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'country',
                'ordering': ['code'],
            },
        ),
    ]
