# Generated by Django 6.0.4 on 2026-04-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='document_type',
            field=models.CharField(max_length=20),
        ),
    ]
