# Generated by Django 6.0.4 on 2026-04-10 01:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_country_ref(apps, schema_editor):
    CreditApplication = apps.get_model('applications', 'CreditApplication')
    Country = apps.get_model('countries', 'Country')

    country_map = {c.code.upper(): c.id for c in Country.objects.all()}

    for app in CreditApplication.objects.all().iterator():
        code = (app.country or '').strip().upper()
        country_id = country_map.get(code)
        if country_id is None:
            continue
        CreditApplication.objects.filter(id=app.id).update(country_ref_id=country_id)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_creditapplication_country_and_more'),
        ('countries', '0002_countryvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='countries.country'),
        ),
        migrations.RunPython(backfill_country_ref, migrations.RunPython.noop),
    ]
