# Generated by Django 6.0.4 on 2026-04-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_creditapplication_country_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='country',
        ),
    ]
