# Generated by Django 6.0.4 on 2026-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_applicationstatushistory_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='from_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='to_status',
            field=models.CharField(max_length=50),
        ),
    ]
