flowchart TD

    START(["Request\nPOST / PATCH"])

    AUTH{"¿JWT válido?"}
    E401["401 Unauthorized"]

    GET_VALIDATOR["Obtener validator\npor country code"]

    SUPPORTED{"¿País soportado?"}
    E400_COUNTRY["400 Bad Request\nPaís no soportado"]

    VAL_DOC["Validar documento\nformato por país"]

    DOC_OK{"¿Documento válido?"}
    E422_DOC["422 Unprocessable\nDocumento inválido"]

    FETCH_BANK["Obtener datos bancarios\nproveedor mock por país"]

    BANK_OK{"¿Proveedor respondió?"}
    E502["502 Bad Gateway\nError proveedor bancario"]

    VAL_RULES["Validar reglas financieras\npor país"]

    RULES_OK{"¿Reglas válidas?"}
    E422_RULES["422 Unprocessable\nReglas no cumplidas"]

    PERSIST["Guardar application\n+ bank_provider_data\n+ country_validations"]

    RESPONSE(["201 Created / 200 OK"])

    START --> AUTH
    AUTH -- "No" --> E401
    AUTH -- "Sí" --> GET_VALIDATOR
    GET_VALIDATOR --> SUPPORTED
    SUPPORTED -- "No" --> E400_COUNTRY
    SUPPORTED -- "Sí" --> VAL_DOC
    VAL_DOC --> DOC_OK
    DOC_OK -- "No" --> E422_DOC
    DOC_OK -- "Sí" --> FETCH_BANK
    FETCH_BANK --> BANK_OK
    BANK_OK -- "No" --> E502
    BANK_OK -- "Sí" --> VAL_RULES
    VAL_RULES --> RULES_OK
    RULES_OK -- "No" --> E422_RULES
    RULES_OK -- "Sí" --> PERSIST
    PERSIST --> RESPONSE

    style START fill:#D3D1C7,stroke:#5F5E5A,color:#2C2C2A
    style RESPONSE fill:#C0DD97,stroke:#3B6D11,color:#173404
    style E401 fill:#F09595,stroke:#A32D2D,color:#501313
    style E400_COUNTRY fill:#F09595,stroke:#A32D2D,color:#501313
    style E422_DOC fill:#F09595,stroke:#A32D2D,color:#501313
    style E502 fill:#FAC775,stroke:#854F0B,color:#412402
    style E422_RULES fill:#F09595,stroke:#A32D2D,color:#501313
    style GET_VALIDATOR fill:#CECBF6,stroke:#534AB7,color:#26215C
    style VAL_DOC fill:#CECBF6,stroke:#534AB7,color:#26215C
    style VAL_RULES fill:#CECBF6,stroke:#534AB7,color:#26215C
    style FETCH_BANK fill:#9FE1CB,stroke:#0F6E56,color:#04342C
    style PERSIST fill:#B5D4F4,stroke:#185FA5,color:#042C53